version: 2.1
jobs:
    build:
        working_directory: /app
        docker:
        - image: docker:17.05.0-ce-git
        steps:
        - checkout
        - setup_remote_docker
        - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - run: docker build -t retrobox/worker .
        - run: docker push retrobox/worker
notify:
    webhooks:
    - url: https://skyhook.glitch.me/api/webhooks/547007853400031258/kfphxKmDbx2voBkmejdC1YrGzNzXFE-HNTrn0U1Z8x1Psl-YaL3bemyQr-CYg2vuhAc0/circleci
